name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run linter
        run: deno lint
      - name: Run tests
        run: deno test -A --unstable --coverage=coverage
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: Collect coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.lcov
